"""empty message

Revision ID: 56f8007462be
Revises: 85a3b71c279b
Create Date: 2022-09-15 14:00:59.141197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56f8007462be'
down_revision = '85a3b71c279b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
